--- 
abstract: the swiss army knife of EMK kit readers
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.004
license: perl
name: Email-MIME-Kit-KitReader-SWAK
requires: 
  Email::MIME::Kit: 2.002
  Path::Resolver: 2.000
version: 1.000
